/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 * The GUI package contains classes related to the graphical user interface of the library management system.
 */
package GUI;

import java.sql.Connection;
import library_managament_system.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import library_managament_system.DatabaseConnection;
import javax.swing.JOptionPane;

/**
 * The Return_book class represents the graphical user interface for returning books
 * in the library management system. Users can enter the book barcode to return a book,
 * and the class interacts with the database to check the eligibility of the book for return
 * and updates the book status accordingly.
 * <p>
 * This class includes methods for checking if a book is eligible for return and performing
 * the return operation. It also handles user actions such as clicking the "Return Book"
 * button or navigating back to the home screen.
 * <p>
 * The GUI components include a text field for entering the book barcode, a button for
 * initiating the return process, and a button for returning to the home screen.
 * <p>
 * This class relies on the DatabaseConnection class for establishing a connection to
 * the database.
 * <p>
 * The Return_book class is part of the GUI package in the library management system.
 *


public class Return_book extends javax.swing.JFrame {
    /**
     * Checks if a book is eligible for return based on its barcode.
     *
    
   
  */

    private Connection connection;

    /**
     * Creates new form Return_book
     */
    public Return_book() {
        initComponents();
        connection = new DatabaseConnection().getConnection();
    }

    private boolean isBookEligibleForReturn(String bookBarcode) {
        String sql = "SELECT book_duedate, book_status FROM library_books WHERE book_barcode = ?";

        try ( PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, bookBarcode);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                java.sql.Date dueDate = resultSet.getDate("book_duedate");
                String bookStatus = resultSet.getString("book_status");

                return (dueDate != null) && ("checked out".equals(bookStatus));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return false;
    }

     /**
     * Performs the return operation for a book based on its barcode.
     *
     * @param bookBarcode The barcode of the book to be returned.
     * @return True if the return operation is successful, false otherwise.
     */
    private boolean returnBook(String bookBarcode) {
        String sql = "UPDATE library_books SET book_duedate = NULL, book_status = 'checked in' WHERE book_barcode = ?";

        try ( PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, bookBarcode);
            return statement.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reurn_booksearchbar = new javax.swing.JTextField();
        Returnbook_button = new javax.swing.JButton();
        backtohomebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Library managament system");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter a book barcode to return a book ");

        reurn_booksearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reurn_booksearchbarActionPerformed(evt);
            }
        });

        Returnbook_button.setText("Return book");
        Returnbook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Returnbook_buttonActionPerformed(evt);
            }
        });

        backtohomebutton.setText("back");
        backtohomebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtohomebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(reurn_booksearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Returnbook_button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backtohomebutton)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backtohomebutton)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reurn_booksearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Returnbook_button)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Returnbook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Returnbook_buttonActionPerformed
        // TODO add your handling code here:

        // Get the book barcode entered by the user
        String bookBarcode = reurn_booksearchbar.getText();

        if (bookBarcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a book barcode.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Check if the book is eligible for returning
            if (isBookEligibleForReturn(bookBarcode)) {
                // Perform the return operation
                if (returnBook(bookBarcode)) {
                    JOptionPane.showMessageDialog(this, "Book with barcode " + bookBarcode + " has been returned.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to return the book.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Book with barcode " + bookBarcode + " is not eligible for return.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Returnbook_buttonActionPerformed

    private void reurn_booksearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reurn_booksearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reurn_booksearchbarActionPerformed

    private void backtohomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtohomebuttonActionPerformed
        // TODO add your handling code here:

        Home objhome = new Home();
        objhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backtohomebuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Returnbook_button;
    private javax.swing.JButton backtohomebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField reurn_booksearchbar;
    // End of variables declaration//GEN-END:variables

}
